spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pbd?serverTimezone=UTC&characterEncoding=UTF-8
    username: luke
    password: '0000'
  data:
    web:
      pageable:
        one-indexed-parameters: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

feedImage:
  path: "D:\\dev\\flab\\project\\feedImage"